/** Shared SEO keyword sets for public marketing pages. */
export const SEO_KEYWORDS = {
  core: [
    "Well Health Trade International",
    "Well Health supplements",
    "health supplements Bangladesh",
    "vitamin supplements Dhaka",
    "buy supplements online Bangladesh",
  ],
  home: [
    "Well Health Trade International",
    "health supplements Bangladesh",
    "buy vitamins online Dhaka",
    "clinical premium supplements",
    "omega supplements BD",
    "eye care supplements Bangladesh",
    "wellness products Bangladesh",
    "natural health supplements",
  ],
  shop: [
    "buy health supplements Bangladesh",
    "vitamin shop Dhaka",
    "omega 3 supplements BD",
    "eye care supplements",
    "brain health supplements",
    "Well Health shop",
    "supplements online Bangladesh",
  ],
  contact: [
    "Well Health contact",
    "supplement company contact Dhaka",
    "health supplement support Bangladesh",
    "Well Health phone number",
    "Well Health customer service",
  ],
  distributor: [
    "supplement distributor Bangladesh",
    "health product distributor Dhaka",
    "become supplement distributor BD",
    "Well Health distributor",
    "pharmacy distributor partnership",
  ],
  blog: [
    "wellness blog Bangladesh",
    "supplement tips",
    "health advice Bangladesh",
    "Well Health blog",
    "vitamin guide",
  ],
  about: [
    "Well Health Trade International",
    "health supplements Bangladesh",
    "vitamin supplements Dhaka",
    "clinical premium supplements",
    "wellness brand Bangladesh",
    "supplement company Bangladesh",
    "about Well Health",
  ],
  legal: [
    "Well Health terms",
    "Well Health privacy policy",
    "supplement store policies Bangladesh",
  ],
} as const;
